---
- name: Converge
  hosts: all
  become: false
  vars:
    state: install
    pg_lang: "en"
    pg_locale: "US"
    pg_disable_postgresql_module: false
    ansible_become_method: su
    iac_blueprint:
      postgresql:
        - version: "16"
          instances:
            - name: main16
              roles:
                - name: app_user
                  password: app_password
                  createdb: false
                - name: app_admin
                  password: admin_password
                  createdb: true
              databases:
                - name: appdb16
                  owner: app_admin
                  extensions:
                    - name: pgcrypto
                  access:
                    - name: app_user
                      address: 10.0.0.1/32
                      type: host
                      method: scram-sha-256
              configuration:
                max_connections: 50
        - version: "17"
          instances:
            - name: main17
              roles:
                - name: app_user
                  password: app_password
                  createdb: false
                - name: app_admin
                  password: admin_password
                  createdb: true
              databases:
                - name: appdb17
                  owner: app_admin
                  extensions:
                    - name: pgcrypto
                  access:
                    - name: app_user
                      address: 10.0.0.1/32
                      type: host
                      method: scram-sha-256
              configuration_profile: balanced
              configuration:
                max_connections: 50
        - version: "18"
          instances:
            - name: main18
              roles:
                - name: app_user
                  password: app_password
                  createdb: false
                - name: app_admin
                  password: admin_password
                  createdb: true
              databases:
                - name: appdb18
                  owner: app_admin
                  extensions:
                    - name: pgcrypto
                  access:
                    - name: app_user
                      address: 10.0.0.1/32
                      type: host
                      method: scram-sha-256
              autotuning_profile: balanced
              configuration:
                max_connections: 50
  roles:
    - role: ansible-iac-role-postgresql
