---
- name: Converge
  hosts: all
  become: false
  vars:
    state: install
    pg_lang: "en"
    pg_locale: "US"
    pg_disable_postgresql_module: false
    ansible_become_method: su
    iac_blueprint:
      postgresql:
        - version: "16"
          directories:
            - path: /tmp/pgsql16
              owner: root
              group: root
              mode: "0750"
          files:
            - path: /tmp/pgsql16/example.txt
              content: "molecule\n"
              owner: root
              group: root
              mode: "0640"
          cron:
            - name: pg16_heartbeat
              user: root
              minute: "0"
              hour: "3"
              job: "/bin/true"
              cron_file: pg16_heartbeat
          instances:
            - name: main16
              roles:
                - name: app_user
                  password: app_password
                  createdb: false
                - name: app_admin
                  password: admin_password
                  createdb: true
              databases:
                - name: appdb16
                  owner: app_admin
                  extensions:
                    - name: pgcrypto
                  access:
                    - name: app_user
                      address: 10.0.0.1/32
                      type: host
                      method: scram-sha-256
              configuration:
                max_connections: 50
        - version: "17"
          directories:
            - path: /tmp/pgsql17
              owner: root
              group: root
              mode: "0750"
          files:
            - path: /tmp/pgsql17/example.txt
              content: "molecule\n"
              owner: root
              group: root
              mode: "0640"
          cron:
            - name: pg17_heartbeat
              user: root
              minute: "0"
              hour: "3"
              job: "/bin/true"
              cron_file: pg17_heartbeat
          instances:
            - name: main17
              roles:
                - name: app_user
                  password: app_password
                  createdb: false
                - name: app_admin
                  password: admin_password
                  createdb: true
              databases:
                - name: appdb17
                  owner: app_admin
                  extensions:
                    - name: pgcrypto
                  access:
                    - name: app_user
                      address: 10.0.0.1/32
                      type: host
                      method: scram-sha-256
              configuration_profile: balanced
              configuration:
                max_connections: 50
        - version: "18"
          directories:
            - path: /tmp/pgsql18
              owner: root
              group: root
              mode: "0750"
          files:
            - path: /tmp/pgsql18/example.txt
              content: "molecule\n"
              owner: root
              group: root
              mode: "0640"
          cron:
            - name: pg18_heartbeat
              user: root
              minute: "0"
              hour: "3"
              job: "/bin/true"
              cron_file: pg18_heartbeat
          instances:
            - name: main18
              roles:
                - name: app_user
                  password: app_password
                  createdb: false
                - name: app_admin
                  password: admin_password
                  createdb: true
              databases:
                - name: appdb18
                  owner: app_admin
                  extensions:
                    - name: pgcrypto
                  access:
                    - name: app_user
                      address: 10.0.0.1/32
                      type: host
                      method: scram-sha-256
              autotuning_profile: balanced
              configuration:
                max_connections: 50
  roles:
    - role: ansible-iac-role-postgresql
