---
dependency:
  name: galaxy

driver:
  name: podman

platforms:
  - name: instance-idarsi-rl8
    image: docker.io/idarsi/rockylinux-init:8
    command: /sbin/init
    privileged: true
    pre_build_image: true
    systemd: true
    tty: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: instance-idarsi-rl9
    image: docker.io/idarsi/rockylinux-init:9
    command: /sbin/init
    privileged: true
    pre_build_image: true
    systemd: true
    tty: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
  - name: instance-idarsi-rl10
    image: docker.io/idarsi/rockylinux-init:10
    command: /sbin/init
    privileged: true
    pre_build_image: true
    systemd: true
    tty: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

provisioner:
  name: ansible
  env:
    ANSIBLE_ASYNC_DIR: "${MOLECULE_PROJECT_DIRECTORY}/.ansible_async"
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/.."

verifier:
  name: ansible
